name = "Grammars"
uuid = "4ef9e186-2fe5-4b24-8de7-9f7291f24af7"
authors = ["Sebastijan Dumancic <s.dumancic@tudelft.nl>", "Jaap de Jong <J.deJong-18@student.tudelft.nl>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TreeView = "39424ebd-4cf3-5550-a685-96706a953f40"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
AbstractTrees = "0.4"
DataStructures = "0.17,0.18"
StatsBase = "0.33"
TreeView = "0.5"
JSON = "0.21"
julia = "1"
